#!/usr/bin/env bash
# update-readme.sh — regenerate root README.md from app-tracker.json
# Called automatically by start-app / finish-app / daily-report

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"

python3 - <<'PYEOF'
import json, datetime

TRACKER = '/home/projects/app-ideas-showcase/app-tracker.json'
README   = '/home/projects/app-ideas-showcase/README.md'
BASE_URL = 'https://ecrent.github.io/app-ideas-showcase/apps'
REPO_URL = 'https://github.com/ecrent/app-ideas-showcase'

with open(TRACKER) as f:
    d = json.load(f)

meta  = d['meta']
apps  = d['apps']
today = datetime.date.today().isoformat()

completed  = [a for a in apps if a['status'] == 'completed']
in_prog    = [a for a in apps if a['status'] == 'in-progress']
upcoming   = [a for a in apps if a['status'] == 'upcoming']

tier_label = {1: '🟢 Tier 1 — Beginner', 2: '🟡 Tier 2 — Intermediate', 3: '🔴 Tier 3 — Advanced'}

def status_badge(app):
    if app['status'] == 'completed':
        return '✅'
    elif app['status'] == 'in-progress':
        return '🔨'
    else:
        return '⏳'

def tier_section(tier_num, tier_apps):
    lines = [f"### {tier_label[tier_num]}\n"]
    lines.append('| # | App | Description | Status | Demo |')
    lines.append('|---|-----|-------------|--------|------|')
    for a in tier_apps:
        badge = status_badge(a)
        name  = a['name']
        desc  = a['description']
        idx   = a['index']
        folder = a['folder']
        if a['status'] == 'completed':
            demo = f"[Live]({BASE_URL}/{folder}/)"
            name = f"[{name}]({REPO_URL}/tree/main/apps/{folder})"
        elif a['status'] == 'in-progress':
            demo = '_building_'
        else:
            demo = '—'
        lines.append(f'| {idx:02d} | {name} | {desc} | {badge} | {demo} |')
    return '\n'.join(lines)

progress_pct = round(len(completed) / len(apps) * 100, 1)
progress_bar_filled = int(progress_pct / 5)
progress_bar = '█' * progress_bar_filled + '░' * (20 - progress_bar_filled)

current_name = in_prog[0]['name'] if in_prog else (upcoming[0]['name'] if upcoming else 'Done!')
next_name    = upcoming[0]['name'] if upcoming and not in_prog else (upcoming[1]['name'] if len(upcoming) > 1 and in_prog else '—')

readme = f"""# App Ideas Showcase

> Building all 82 apps from [florinpop17/app-ideas](https://github.com/florinpop17/app-ideas) — one by one.
> Stack: React · TypeScript · Tailwind CSS · Vite · GitHub Pages

## Progress

```
{progress_bar}  {progress_pct}%  ({len(completed)}/{len(apps)} apps)
```

| Stat | Value |
|------|-------|
| Completed | {len(completed)} apps |
| In Progress | {in_prog[0]['name'] if in_prog else '—'} |
| Next Up | {next_name} |
| Last Updated | {today} |

---

{tier_section(1, [a for a in apps if a['tier'] == 1])}

---

{tier_section(2, [a for a in apps if a['tier'] == 2])}

---

{tier_section(3, [a for a in apps if a['tier'] == 3])}

---

<sub>Auto-generated by <code>scripts/update-readme.sh</code> · Last updated: {today}</sub>
"""

with open(README, 'w') as f:
    f.write(readme)

print(f"README updated — {len(completed)} complete, {len(in_prog)} in progress, {len(upcoming)} upcoming")
PYEOF
